export const ADD_PERSON = 'ADD_PERSON'; // UPPER_SNAKE
export const REMOVE_PERSON = 'REMOVE_PERSON'; // UPPER_SNAKE
export const GET_PERSON_ID = 'GET_PERSON_ID'; // UPPER_SNAKE
export const GET_PERSON_NAME = 'GET_PERSON_NAME'; // UPPER_SNAKE